// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "./_components/ui/sonner";
import AuthProvider from "./_providers/auth";
// Importado para consistência, mas não usado aqui
// import Footer from "./_components/ui/Footer";
import Header from "./_components/ui/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <AuthProvider>
          <div className="flex flex-col h-full">
            <Header /> {/* Adicionado Header para contexto */}
            <div className="flex-1">{children}</div>
            {/* Removido o Footer para evitar inconsistências */}
          </div>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}